#include "azerty"
// #include "qwerty"
// #include "dvorak"
// #include "colman"

#include "functions"
#include "hardware"
#include "media"
#include "navigation"
#include "numbers"
#include "special"
// #include "symbols"
#include "symbols_l"
#include "symbols_r"
