#define a_grave    &mt_a_grave
#define e_grave    &mt_e_grave
#define u_grave    &mt_u_grave
#define a_ccmflx   &mt_a_ccmflx
#define e_ccmflx   &mt_e_ccmflx
#define i_ccmflx   &mt_i_ccmflx
#define o_ccmflx   &mt_o_ccmflx
#define u_ccmflx   &mt_u_ccmflx
#define a_trema    &mt_a_trema
#define e_trema    &mt_e_trema
#define i_trema    &mt_i_trema
#define o_trema    &mt_o_trema
#define u_trema    &mt_u_trema
#define e_cute     &mt_e_cute
#define c_cedilla  &mt_c_cedilla
#define euro       &mt_euro
#define pound      &mt_pound
#define degree     &mt_degree
#define trademark  &mt_trademark
#define copyright  &mt_copyright
